In [ ]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf

In [ ]:
# First Task: Creating a TensorFlow constant

# Creating a constant tensor with values [1, 2, 3]
constant_tensor = tf.constant([1, 2, 3])

# Printing the constant tensor
print("The Constant Tensor is -", constant_tensor)


The Constant Tensor is - tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
# Second Task: Performing element wise multiplication

# Defining the tensors
a = tf.constant([2, 4, 6])
b = tf.constant([1, 2, 3])

# Performing the multiplication
product = tf.multiply(a, b)

# Printing the result
print(product)


tf.Tensor([ 2  8 18], shape=(3,), dtype=int32)


In [ ]:
# Third Task: Reshaping a tensor

# Define the 1D tensor
x = tf.constant([1, 2, 3, 4, 5, 6])

# Reshape the tensor into a 2D tensor with 2 rows and 3 columns
reshaped_x = tf.reshape(x, (2, 3))

# Print the reshaped tensor
print(reshaped_x)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# Fourth Task: Extracting a column

# Define the 2D tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract the middle column
middle_column = matrix[:, 1]

# Print the result
print(middle_column)


tf.Tensor([2 5 8], shape=(3,), dtype=int32)
